create table mindvault_subject (
    id bigint generated by default as identity,
    user_id bigint not null,
    title varchar(255) not null,
    description text,
    priority integer not null,
    target_mastery integer not null,
    deadline date,
    tags varchar(1000),
    archived boolean not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_mindvault_subject_user foreign key (user_id) references app_user(id)
);

create table mindvault_sprint (
    id bigint generated by default as identity,
    user_id bigint not null,
    subject_id bigint,
    title varchar(255) not null,
    description text,
    status varchar(50) not null,
    start_date date,
    due_date date,
    estimated_sessions integer not null,
    completed_sessions integer not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_mindvault_sprint_user foreign key (user_id) references app_user(id),
    constraint fk_mindvault_sprint_subject foreign key (subject_id) references mindvault_subject(id)
);

create table mindvault_learning_item (
    id bigint generated by default as identity,
    user_id bigint not null,
    subject_id bigint,
    sprint_id bigint,
    source varchar(50) not null,
    title varchar(255) not null,
    prompt text,
    answer text,
    notes text,
    tags varchar(1000),
    priority integer not null,
    difficulty integer not null,
    mastery_score integer not null,
    review_streak integer not null,
    review_count integer not null,
    success_count integer not null,
    ease_factor double precision not null,
    review_interval_days integer not null,
    next_review_date date,
    last_reviewed_at timestamp(6),
    last_rating integer,
    status varchar(50) not null,
    due_date date,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_mindvault_item_user foreign key (user_id) references app_user(id),
    constraint fk_mindvault_item_subject foreign key (subject_id) references mindvault_subject(id),
    constraint fk_mindvault_item_sprint foreign key (sprint_id) references mindvault_sprint(id)
);

create table mindvault_review_log (
    id bigint generated by default as identity,
    user_id bigint not null,
    item_id bigint not null,
    rating integer not null,
    previous_interval_days integer,
    next_interval_days integer,
    mastery_after integer,
    ease_factor_after double precision,
    note text,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_mindvault_review_user foreign key (user_id) references app_user(id),
    constraint fk_mindvault_review_item foreign key (item_id) references mindvault_learning_item(id)
);

create index idx_mindvault_subject_user on mindvault_subject(user_id);
create index idx_mindvault_sprint_user on mindvault_sprint(user_id);
create index idx_mindvault_item_user on mindvault_learning_item(user_id);
create index idx_mindvault_item_subject on mindvault_learning_item(subject_id);
create index idx_mindvault_item_sprint on mindvault_learning_item(sprint_id);
create index idx_mindvault_item_next_review on mindvault_learning_item(next_review_date);
create index idx_mindvault_review_user on mindvault_review_log(user_id);
