alter table habit_item alter column cadence set default 'DAILY';
alter table habit_item alter column target_count set default 1;
alter table habit_item alter column streak set default 0;
alter table habit_item alter column completed_count set default 0;

alter table habit_item add column if not exists description text;
alter table habit_item add column if not exists habit_type varchar(50) not null default 'BUILD';
alter table habit_item add column if not exists schedule_type varchar(50) not null default 'DAILY';
alter table habit_item add column if not exists scheduled_days varchar(60) not null default '1,2,3,4,5,6,7';
alter table habit_item add column if not exists target_value double precision;
alter table habit_item add column if not exists target_unit varchar(80);
alter table habit_item add column if not exists reminder_time time;
alter table habit_item add column if not exists start_date date not null default current_date;
alter table habit_item add column if not exists end_date date;
alter table habit_item add column if not exists tags varchar(1000);
alter table habit_item add column if not exists color varchar(32) not null default '#4be1c3';
alter table habit_item add column if not exists priority integer not null default 3;
alter table habit_item add column if not exists paused boolean not null default false;
alter table habit_item add column if not exists cue text;
alter table habit_item add column if not exists routine text;
alter table habit_item add column if not exists reward text;
alter table habit_item add column if not exists friction text;
alter table habit_item add column if not exists identity_statement text;

update habit_item
set
    habit_type = coalesce(habit_type, 'BUILD'),
    schedule_type = case when cadence = 'WEEKLY' then 'WEEKLY' when cadence = 'CUSTOM' then 'CUSTOM' else 'DAILY' end,
    scheduled_days = case when cadence = 'DAILY' then '1,2,3,4,5,6,7' else scheduled_days end,
    target_value = coalesce(target_value, target_count::double precision),
    target_unit = coalesce(target_unit, 'times'),
    priority = coalesce(priority, 3),
    color = coalesce(color, '#4be1c3'),
    start_date = coalesce(start_date, created_at::date);

create table if not exists habit_checkin (
    id bigint generated by default as identity,
    user_id bigint not null,
    habit_id bigint not null,
    checkin_date date not null,
    status varchar(50) not null,
    checkin_value double precision,
    note text,
    mood integer,
    energy integer,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_habit_checkin_user foreign key (user_id) references app_user(id),
    constraint fk_habit_checkin_habit foreign key (habit_id) references habit_item(id) on delete cascade,
    constraint uk_habit_checkin_habit_date unique (habit_id, checkin_date)
);

create index if not exists idx_habit_checkin_user_date on habit_checkin(user_id, checkin_date);
create index if not exists idx_habit_checkin_habit_date on habit_checkin(habit_id, checkin_date);
