create table if not exists smaart_goal (
    id bigint generated by default as identity,
    user_id bigint not null,
    goal_type varchar(50) not null default 'SHORT_TERM',
    status varchar(50) not null default 'TODO',
    title varchar(255) not null,
    description text,
    category varchar(120),
    priority integer not null default 3,
    start_date date,
    deadline date not null,
    motivation text,
    success_criteria text,
    notes text,
    specific_text text,
    measurable_text text,
    achievable_text text,
    action_oriented_text text,
    relevant_text text,
    time_bound_text text,
    migrated_goal_id bigint,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_smaart_goal_user foreign key (user_id) references app_user(id),
    constraint uk_smaart_goal_migrated_goal unique (migrated_goal_id)
);

create table if not exists smaart_sprint (
    id bigint generated by default as identity,
    user_id bigint not null,
    goal_id bigint not null,
    title varchar(255) not null,
    objective text,
    start_date date,
    end_date date,
    status varchar(50) not null default 'TODO',
    notes text,
    sort_order integer not null default 0,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_smaart_sprint_user foreign key (user_id) references app_user(id),
    constraint fk_smaart_sprint_goal foreign key (goal_id) references smaart_goal(id) on delete cascade
);

create table if not exists smaart_task (
    id bigint generated by default as identity,
    user_id bigint not null,
    goal_id bigint not null,
    sprint_id bigint,
    title varchar(255) not null,
    description text,
    status varchar(50) not null default 'TODO',
    priority integer not null default 3,
    due_date date,
    estimated_minutes integer,
    completed boolean not null default false,
    tags varchar(1000),
    notes text,
    sort_order integer not null default 0,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_smaart_task_user foreign key (user_id) references app_user(id),
    constraint fk_smaart_task_goal foreign key (goal_id) references smaart_goal(id) on delete cascade,
    constraint fk_smaart_task_sprint foreign key (sprint_id) references smaart_sprint(id) on delete set null
);

create table if not exists smaart_task_checklist_item (
    id bigint generated by default as identity,
    user_id bigint not null,
    task_id bigint not null,
    title varchar(255) not null,
    completed boolean not null default false,
    sort_order integer not null default 0,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_smaart_checklist_user foreign key (user_id) references app_user(id),
    constraint fk_smaart_checklist_task foreign key (task_id) references smaart_task(id) on delete cascade
);

create table if not exists smaart_task_dependency (
    id bigint generated by default as identity,
    user_id bigint not null,
    task_id bigint not null,
    depends_on_task_id bigint not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_smaart_dependency_user foreign key (user_id) references app_user(id),
    constraint fk_smaart_dependency_task foreign key (task_id) references smaart_task(id) on delete cascade,
    constraint fk_smaart_dependency_depends foreign key (depends_on_task_id) references smaart_task(id) on delete cascade,
    constraint uk_smaart_task_dependency_pair unique (task_id, depends_on_task_id)
);

create table if not exists smaart_activity_log (
    id bigint generated by default as identity,
    user_id bigint not null,
    goal_id bigint,
    sprint_id bigint,
    task_id bigint,
    activity_action varchar(120) not null,
    description text,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_smaart_activity_user foreign key (user_id) references app_user(id),
    constraint fk_smaart_activity_goal foreign key (goal_id) references smaart_goal(id) on delete cascade,
    constraint fk_smaart_activity_sprint foreign key (sprint_id) references smaart_sprint(id) on delete cascade,
    constraint fk_smaart_activity_task foreign key (task_id) references smaart_task(id) on delete cascade
);

create index if not exists idx_smaart_goal_user_status on smaart_goal(user_id, status);
create index if not exists idx_smaart_sprint_goal on smaart_sprint(goal_id);
create index if not exists idx_smaart_task_goal on smaart_task(goal_id);
create index if not exists idx_smaart_task_sprint on smaart_task(sprint_id);
create index if not exists idx_smaart_task_due on smaart_task(user_id, due_date);
create index if not exists idx_smaart_activity_goal on smaart_activity_log(goal_id, created_at);

insert into smaart_goal (
    user_id,
    goal_type,
    status,
    title,
    description,
    category,
    priority,
    start_date,
    deadline,
    motivation,
    success_criteria,
    specific_text,
    measurable_text,
    achievable_text,
    action_oriented_text,
    relevant_text,
    time_bound_text,
    migrated_goal_id,
    created_at,
    updated_at
)
select
    gi.user_id,
    'SHORT_TERM',
    case
        when gi.status = 'DONE' then 'COMPLETED'
        when gi.status = 'IN_PROGRESS' then 'IN_PROGRESS'
        when gi.status = 'BLOCKED' then 'BLOCKED'
        else 'TODO'
    end,
    gi.title,
    gi.description,
    'Migrated',
    gi.priority,
    coalesce(cast(gi.created_at as date), current_date),
    coalesce(gi.due_date, current_date),
    'Migrated from the earlier lightweight goals tracker.',
    'Use tasks to define completion.',
    gi.title,
    'Completion is measured by task progress.',
    'Imported with safe defaults.',
    'Break this goal into clear tasks.',
    'Preserved from the previous FlowDash goals model.',
    coalesce(cast(gi.due_date as varchar), 'No original due date'),
    gi.id,
    gi.created_at,
    gi.updated_at
from goal_item gi
where not exists (
    select 1 from smaart_goal sg where sg.migrated_goal_id = gi.id
);
