alter table smaart_task add column if not exists category varchar(120);
alter table smaart_task add column if not exists urgency integer not null default 3;
alter table smaart_task add column if not exists importance integer not null default 3;
alter table smaart_task add column if not exists impact integer not null default 3;
alter table smaart_task add column if not exists effort integer not null default 3;

create table if not exists smaart_priority_profile (
    id bigint generated by default as identity,
    user_id bigint not null,
    urgency_weight integer not null default 1,
    importance_weight integer not null default 1,
    deadline_weight integer not null default 1,
    effort_weight integer not null default 1,
    impact_weight integer not null default 1,
    high_priority_threshold integer not null default 75,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_smaart_priority_profile_user foreign key (user_id) references app_user(id) on delete cascade,
    constraint uk_smaart_priority_profile_user unique (user_id)
);
